(lang dune 3.19)

(name tinysol-lang)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Group id: G14
          Matteo Parasuco 66469
          Pietro Pillola 66399
          Danilo Marras 66408
          Marta Podda 66517")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name tinysol-lang)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

(using menhir 2.1)

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
